In [1]:
import torch
print(torch.__version__)

1.13.0+cu116


#TENSORS

In [4]:
my_tensor = torch.tensor([[1,2,3], [4,5,6]], dtype = torch.float32)#device = "cuda" or "cpu"
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [5]:
my_tensor.dtype

torch.float32

In [6]:
my_tensor.device

device(type='cpu')

In [7]:
my_tensor.shape

torch.Size([2, 3])

In [9]:
my_tensor.requires_grad

False

### Other common initialisers

In [12]:
torch.empty(size = (3,3)) # values in memeory so random data

tensor([[1.8450e-34, 0.0000e+00, 3.5032e-44],
        [0.0000e+00,        nan, 6.4460e-44],
        [1.1578e+27, 7.1463e+22, 4.6241e+30]])

In [13]:
torch.zeros((3,3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [14]:
torch.rand((3,3))

tensor([[0.6365, 0.6269, 0.5715],
        [0.6133, 0.4445, 0.3035],
        [0.4307, 0.9649, 0.8637]])

In [15]:
torch.ones((3,3))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [17]:
torch.eye(3,3) # identity matrix

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [19]:
torch.arange(start = 0, end = 5, step = 1)

tensor([0, 1, 2, 3, 4])

In [20]:
torch.linspace(start = 0.1, end = 1, steps = 100)

tensor([0.1000, 0.1091, 0.1182, 0.1273, 0.1364, 0.1455, 0.1545, 0.1636, 0.1727,
        0.1818, 0.1909, 0.2000, 0.2091, 0.2182, 0.2273, 0.2364, 0.2455, 0.2545,
        0.2636, 0.2727, 0.2818, 0.2909, 0.3000, 0.3091, 0.3182, 0.3273, 0.3364,
        0.3455, 0.3545, 0.3636, 0.3727, 0.3818, 0.3909, 0.4000, 0.4091, 0.4182,
        0.4273, 0.4364, 0.4455, 0.4545, 0.4636, 0.4727, 0.4818, 0.4909, 0.5000,
        0.5091, 0.5182, 0.5273, 0.5364, 0.5455, 0.5545, 0.5636, 0.5727, 0.5818,
        0.5909, 0.6000, 0.6091, 0.6182, 0.6273, 0.6364, 0.6455, 0.6545, 0.6636,
        0.6727, 0.6818, 0.6909, 0.7000, 0.7091, 0.7182, 0.7273, 0.7364, 0.7455,
        0.7545, 0.7636, 0.7727, 0.7818, 0.7909, 0.8000, 0.8091, 0.8182, 0.8273,
        0.8364, 0.8455, 0.8545, 0.8636, 0.8727, 0.8818, 0.8909, 0.9000, 0.9091,
        0.9182, 0.9273, 0.9364, 0.9455, 0.9545, 0.9636, 0.9727, 0.9818, 0.9909,
        1.0000])

In [22]:
torch.empty(size=(1,5)).normal_(mean = 0, std =1) # values normally distributed with mean of 0 and stadard deviation of 1

tensor([[ 0.6708, -1.0394,  2.7900, -0.5111, -0.3857]])

In [26]:
 torch.empty(size=(1,5)).uniform_(0,1) # uniform distribution between 0 and 1

tensor([[0.8961, 0.6399, 0.2545, 0.8269, 0.8796]])

In [27]:
torch.diag(torch.ones(3))

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

### initialise tensors to different types



In [30]:
 tensor = torch.arange(4)
 tensor

tensor([0, 1, 2, 3])

In [31]:
tensor.bool()

tensor([False,  True,  True,  True])

In [32]:
 tensor.short()

tensor([0, 1, 2, 3], dtype=torch.int16)

In [33]:
tensor.long()

tensor([0, 1, 2, 3])

In [34]:
tensor.half()

tensor([0., 1., 2., 3.], dtype=torch.float16)

In [35]:
tensor.float()

tensor([0., 1., 2., 3.])

In [36]:
tensor.double()

tensor([0., 1., 2., 3.], dtype=torch.float64)

###Numpy Array to tensor and vice versa

In [37]:
import numpy as np

In [40]:
arr = np.zeros((5, 5))
tensor = torch.from_numpy(arr)
tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)

In [41]:
tensor.numpy()

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Tensor Math and comparision oporations

In [46]:
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])

# Addition
z1 = torch.empty(3)
z1 = torch.add(x, y)
z1

tensor([10, 10, 10])

In [47]:
x+y

tensor([10, 10, 10])

In [48]:
x-y

tensor([-8, -6, -4])

In [49]:
x/y

tensor([0.1111, 0.2500, 0.4286])

In [50]:
t = torch.zeros(3)
t.add_(x) # underscre represents inplace operation

tensor([1., 2., 3.])

In [52]:
t += x
t

tensor([3., 6., 9.])

In [55]:
#Exponentiaiton
x.pow(2) #Elemnt wise
x**2

tensor([1, 4, 9])

In [57]:
z = x>1
z

tensor([False,  True,  True])

In [58]:
# matrix multiplicaton
x1 = torch.rand((2,5))
x2 = torch.rand((5,3))
x3 = torch.mm(x1, x2)
x3

tensor([[0.8590, 0.8493, 1.0180],
        [0.6386, 0.4846, 0.9584]])

In [59]:
matrix_exp = torch.rand(5, 5)
matrix_exp.matrix_power(3)

tensor([[6.5702, 6.1619, 3.4248, 4.7458, 2.5398],
        [7.1198, 6.6649, 3.6772, 5.1403, 2.7197],
        [4.7899, 4.3824, 2.4272, 3.4923, 1.7885],
        [5.0830, 4.8834, 2.6439, 3.6269, 1.9971],
        [5.7337, 5.3324, 2.9059, 4.1456, 2.1309]])

In [61]:
# element wise mult
x * y

tensor([ 9, 16, 21])

In [63]:
# dot product: Element wise and the sumation of all the values so 9+12+21
torch.dot(x, y)

tensor(46)